# Generated by Django 4.1.1 on 2022-10-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anunciante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_anunciante', models.CharField(max_length=256)),
                ('email_anunciante', models.CharField(max_length=256)),
                ('password_anunciante', models.CharField(max_length=256)),
                ('token_api', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_marca', models.CharField(max_length=100)),
                ('nome_modelo', models.CharField(max_length=100)),
                ('ano', models.CharField(max_length=4)),
                ('cor', models.CharField(max_length=100)),
                ('anunciado_por', models.CharField(max_length=100)),
            ],
        ),
    ]
