# Generated by Django 4.1.1 on 2022-09-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_veiculo', models.CharField(max_length=100)),
                ('nome_marca', models.CharField(max_length=100)),
                ('nome_modelo', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=100)),
            ],
        ),
    ]
