# Generated by Django 4.1.1 on 2022-09-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anunciante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_anunciante', models.CharField(max_length=256)),
                ('email_anunciante', models.CharField(max_length=256)),
                ('password_anunciante', models.CharField(max_length=256)),
                ('token_api', models.CharField(max_length=256)),
            ],
        ),
    ]
